# Generated by Django 4.1.2 on 2025-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Real Name'),
        ),
    ]
