# Generated by Django 4.1.2 on 2025-04-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_listmodel_check_code_alter_listmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmodel',
            name='check_code',
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='error_check_code_counter',
        ),
    ]
