# Generated by Django 4.1.2 on 2025-04-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_listmodel_check_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmodel',
            name='password',
        ),
    ]
