# Generated by Django 4.1.2 on 2025-04-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键名')),
                ('value', models.TextField(verbose_name='设置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
    ]
